"""Initial migration with reset_token

Revision ID: 2b0c325c5d9f
Revises: 
Create Date: 2025-03-07 18:42:01.164772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0c325c5d9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('hypertension', sa.Integer(), nullable=True),
    sa.Column('diabetes', sa.Integer(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('fitness_goal', sa.Integer(), nullable=True),
    sa.Column('fitness_type', sa.Integer(), nullable=True),
    sa.Column('exercises', sa.String(length=200), nullable=True),
    sa.Column('diet', sa.String(length=200), nullable=True),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))

    op.drop_table('user')
    # ### end Alembic commands ###
